namespace VoiceChatPlugin.VoiceChat;

internal enum VoiceProximityReason
{
    Lobby,
    Unmapped,
    NoListener,
    OnlyMeetingOrLobby,
    OnlyGhostsCanTalk,
    CommsSabotage,
    LocalDeadHearsGhost,
    LocalDeadHearsLiving,
    Blackmailed,
    BlackmailedNextRound,
    Jailed,
    ParasiteControlled,
    PuppeteerControlled,
    Swooped,
    MeetingLiving,
    TeamRadio,
    TeamRadioMuted,
    ImpostorHearsGhost,
    TargetDeadMuted,
    VentMuted,
    VentPrivateMuted,
    SightBlocked,
    HardOcclusion,
    CameraProxy,
    Proximity,
}
